version: '3.3'

networks:
  eats-network:
    driver: bridge

volumes:
  mysql.eats.pagamento:
  mongo.eats.distancia:

services:
  eats-application-mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart:
      unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: eats
    ports:
      - "3307:3306"
    networks:
      - eats-network

  eats-pagamento-mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart:
      unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: caelum123
      MYSQL_DATABASE: eats_pagamento
      MYSQL_USER: pagamento
      MYSQL_PASSWORD: pagamento123
    volumes:
      - mysql.eats.pagamento:/var/lib/mysql
    networks:
      - eats-network

  eats-distancia-mongo-db:
    image: mongo:3.6
    ports:
      - "27018:27017"
    volumes:
      - mongo.eats.distancia:/data/db
    networks:
      - eats-network

  eats-pagamento-service:
    build: ./eats-pagamento-service
    ports:
      - "8081:8081"
    tty:
      true
    restart:
      unless-stopped
    networks:
      - eats-network
    depends_on:
      - eats-pagamento-mysql-db
    environment:
      DATABASE_HOST: eats-pagamento-mysql-db
      DATABASE_USER: pagamento
      DATABASE_PASSWORD: pagamento123
      DATABASE_NAME: eats_pagamento
      DATABASE_PORT: 3306
      SPRING_PROFILES_ACTIVE: "docker-mysql"
      SERVER_PORT: "8081"
      PEDIDO_SERVICE_URL: "http://eats-application:8080"

  eats-distancia-service:
    build: ./eats-distancia-service
    ports:
      - "8082:8082"
    tty:
      true
    restart:
      unless-stopped
    networks:
      - eats-network
    depends_on:
      - eats-distancia-mongo-db
    environment:
      DATABASE_HOST: "eats-distancia-mongo-db"
      DATABASE_NAME: "eats_distancia"
      DATABASE_PORT: "27017"
      SPRING_PROFILES_ACTIVE: "docker-mongodb"
      SERVER_PORT: "8082"

  eats-application:
    build: ./eats-application
    ports:
      - "8080:8080"
    tty:
      true
    restart:
      unless-stopped
    networks:
      - eats-network
    depends_on:
      - eats-application-mysql-db
    environment:
      DATABASE_HOST: "eats-application-mysql-db"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "caelum123"
      DATABASE_NAME: "eats"
      DATABASE_PORT: "3306"
      SPRING_PROFILES_ACTIVE: "docker-mysql"
      SERVER_PORT: "8080"
      DISTANCIA_SERVICE_URL: "http://eats-distancia-service:8082"

  eats-ui:
    build: ./eats-ui
    ports:
      - "4200:80"
    tty:
      true
    restart:
      unless-stopped
    networks:
      - eats-network

